openapi: 3.0.0
info:
  title: OneTrust Inventory API
  description: API to interact with inventory assets in the OneTrust system.
  version: 1.0.0
servers:
  - url: https://uat.onetrust.com/api/inventory/v2
    description: OneTrust UAT Environment
paths:
  /inventories/{inventoryType}/{assetId}:
    get:
      operationId: GetAssetById
      summary: Retrieve an asset by its ID.
      description: Fetches the details of a specific asset from the OneTrust inventory using the provided asset ID.
      parameters:
        - name: inventoryType
          in: path
          required: true
          description: The type of inventory to query, options are assets, vendors, processing-activities, entities .
          schema:
            type: string
        - name: assetId
          in: path
          required: true
          description: The unique identifier of the asset to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the asset.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the asset.
                  name:
                    type: string
                    description: The name of the asset.
                  type:
                    type: string
                    description: The type or category of the asset.
                  status:
                    type: string
                    description: The status of the asset.
                  metadata:
                    type: object
                    description: Additional metadata about the asset.
        '400':
          description: Bad request, possibly due to a missing or invalid asset ID.
        '404':
          description: Asset not found for the given ID.
        '500':
          description: Internal server error.
  /inventories/{inventoryType}:
    get:
      operationId: GetAssetsList
      summary: Retrieve a list of all inventory objects by type. 
      description: Fetches a list of assets from the OneTrust inventory.
      parameters:
        - name: inventoryType
          in: path
          required: true
          description: The type of inventory to query, options are assets, vendors, processing-activities, entities .
          schema:
            type: string
        - name: page
          in: query
          required: true
          description: The page number for paginated results.
          schema:
            type: integer
            minimum: 1
        - name: pageSize
          in: query
          required: true
          description: The number of items to include per page for paginated results.
          schema:
            type: integer
            minimum: 100
        - name: filter
          in: query
          required: false
          description: Filter criteria to apply to the list of assets.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the list of assets.
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier of the asset.
                        name:
                          type: string
                          description: The name of the asset.
                        type:
                          type: string
                          description: The type or category of the asset.
                        status:
                          type: string
                          description: The status of the asset.
                        metadata:
                          type: object
                          description: Additional metadata about the asset.
                  totalItems:
                    type: integer
                    description: The total number of assets available.
                  totalPages:
                    type: integer
                    description: The total number of pages available.
                  currentPage:
                    type: integer
                    description: The current page number.
        '400':
          description: Bad request, possibly due to invalid query parameters.
        '500':
          description: Internal server error.
