Descriptor:
  Name: InventoryPlugin
  DisplayName: OneTrust Data Mapping Inventory Plugin
  Description: This plugin can query the onetrust data mapping inventory for assets, vendors, entities, and processing activities.
  SupportedAuthTypes:
    - ApiKey
  Authorization:
    Type: APIKey
    Key: Authorization
    Location: Header
    AuthScheme: 'Bearer '

SkillGroups:
  - Format: API
    Settings:
      OpenApiSpecUrl: https://raw.githubusercontent.com/kevinmjones/mscp/cd0d9fce30e246fe01eae01e767043a25d058d9c/Inventory/inventoryapi.yaml
