openapi: 3.0.0
info:
  title: Purview Discovery Query API
  version: "2023-09-01"
  description: >
    This API allows you to get data using search from Azure Purview.
    It supports filtering, faceting, and ordering search results.
servers:
  - url: https://{endpoint}/datamap/api
    description: Purview endpoint
    variables:
      endpoint:
        default: "your-purview-endpoint"
        description: The fully qualified host name for your Purview account.
paths:
  /search/query:
    post:
      summary: Discovery Query
      description: Get data using search.
      operationId: discoveryQuery
      parameters:
        - name: api-version
          in: query
          description: The API version to use for this operation.
          required: true
          schema:
            type: string
            example: "2023-09-01"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                continuationToken:
                  type: string
                  description: >
                    The token used to get the next batch of data.
                    Use null (or omit) to retrieve the first batch.
                facets:
                  type: array
                  description: The facets for search. See examples for supported facets.
                  items:
                    $ref: '#/components/schemas/SearchFacetItem'
                filter:
                  type: object
                  description: >
                    The filter for the search. Supports logical operators (and/or) and attribute filtering.
                  additionalProperties: true
                keywords:
                  type: string
                  description: The keywords applied to all searchable fields.
                limit:
                  type: integer
                  description: >
                    The maximum number of search results to return. Default is 50; maximum is 1000.
                  default: 50
                  maximum: 1000
                orderby:
                  type: array
                  description: >
                    The sort order of search results. Multiple fields can be specified.
                  items:
                    $ref: '#/components/schemas/OrderbyItem'
                taxonomySetting:
                  type: object
                  description: The taxonomy setting for search.
                  additionalProperties: true
              example:
                keywords: "exampledata"
                filter:
                  and:
                    - entityType: "azure_blob_path"
                    - attributeName: "qualifiedName"
                      operator: "contains"
                      attributeValue: ".csv"
                limit: 10
                orderby:
                  - name: "ASC"
                  - updateTime: "DESC"
                facets:
                  - facet: "assetType"
                    count: 0
                    sort:
                      count: "desc"
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  "@search.count":
                    type: integer
                  "@search.count.approximate":
                    type: boolean
                  continuationToken:
                    type: string
                    description: Token for next page, if available.
                  "@search.facets":
                    type: object
                    description: Facet information.
                    additionalProperties:
                      type: array
                      items:
                        type: object
                        properties:
                          count:
                            type: integer
                          value:
                            type: string
                  value:
                    type: array
                    description: List of search result items.
                    items:
                      $ref: '#/components/schemas/SearchResultItem'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AtlasErrorResponse'
      security:
        - OAuth2Auth: []
components:
  schemas:
    SearchFacetItem:
      type: object
      properties:
        facet:
          type: string
          description: The facet field name.
        count:
          type: integer
          description: The count of results for the facet.
        sort:
          type: object
          description: The sort order for the facet.
          properties:
            count:
              type: string
              enum: [asc, desc]
      required:
        - facet
        - count
    OrderbyItem:
      type: object
      description: An object representing a field and its sort order.
      additionalProperties:
        type: string
        enum: [ASC, DESC, asc, desc]
    SearchResultItem:
      type: object
      properties:
        "@search.score":
          type: number
          description: The search score.
        "@search.highlights":
          type: object
          description: Fields highlighting matching text.
          additionalProperties:
            type: array
            items:
              type: string
        id:
          type: string
        qualifiedName:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        owner:
          type: string
          nullable: true
        entityType:
          type: string
        classification:
          type: array
          items:
            type: string
        label:
          type: array
          items:
            type: string
        assetType:
          type: array
          items:
            type: string
        term:
          type: array
          items:
            type: string
        contact:
          type: array
          items:
            type: string
    AtlasErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
      required:
        - error
  securitySchemes:
    OAuth2Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://login.microsoftonline.com/common/oauth2/authorize"
          scopes:
            "https://purview.azure.net/.default": "Access Purview resources"
